/** JSON Schema pre Mistral structured output (json_schema + strict). */

const EVIDENCE_TYPES = [
  "direct_evidence",
  "testimony",
  "corroborated",
  "inference",
  "hypothesis",
] as const;

const WEAPONS_ROLES = [
  "orderer",
  "buyer",
  "buyer_entity",
  "payer",
  "invoice_payer",
  "cash_payer",
  "account_holder",
  "funding_source",
  "intermediary",
  "physical_receiver",
  "alleged_next_recipient",
  "transporter",
  "storage_holder",
  "seller",
  "transferor",
  "final_holder",
  "unknown",
] as const;

const evidenceSchema = {
  type: "object",
  additionalProperties: false,
  required: ["document_id", "page", "quote", "evidence_type"],
  properties: {
    document_id: { type: "string" },
    page: { type: ["integer", "number", "null"] },
    quote: { type: "string" },
    evidence_type: { type: "string", enum: [...EVIDENCE_TYPES] },
    linear_project_id: { type: "string" },
    linear_issue_id: { type: ["string", "null"] },
    linear_document_id: { type: ["string", "null"] },
    attachment_id: { type: ["string", "null"] },
    source_group_id: { type: ["string", "null"] },
  },
} as const;

const actorSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "entity_id",
    "name",
    "entity",
    "entity_kind",
    "role",
    "found_in_text",
    "inferred",
    "confidence",
    "evidence",
    "contradicting_evidence",
  ],
  properties: {
    entity_id: { type: "string" },
    name: { type: "string" },
    entity: { type: ["string", "null"] },
    entity_kind: { type: "string", enum: ["person", "company", "other"] },
    role: { type: "string", enum: [...WEAPONS_ROLES] },
    found_in_text: { type: "boolean" },
    inferred: { type: "boolean" },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    evidence: { type: "array", items: evidenceSchema },
    contradicting_evidence: { type: "array", items: evidenceSchema },
  },
} as const;

const planCandidateSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "entity_id",
    "name",
    "entity",
    "entity_kind",
    "role",
    "found_in_text",
    "inferred",
    "confidence",
    "evidence",
    "contradicting_evidence",
  ],
  properties: {
    entity_id: { type: "string" },
    name: { type: "string" },
    entity: { type: ["string", "null"] },
    entity_kind: { type: "string", enum: ["person", "company", "other"] },
    role: {
      type: "string",
      enum: ["designer", "director", "coordinator", "unknown"],
    },
    found_in_text: { type: "boolean" },
    inferred: { type: "boolean" },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    evidence: { type: "array", items: evidenceSchema },
    contradicting_evidence: { type: "array", items: evidenceSchema },
  },
} as const;

const payerSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "entity_id",
    "name",
    "entity",
    "entity_kind",
    "role",
    "found_in_text",
    "inferred",
    "confidence",
    "evidence",
  ],
  properties: {
    entity_id: { type: "string" },
    name: { type: "string" },
    entity: { type: ["string", "null"] },
    entity_kind: { type: "string", enum: ["person", "company", "other"] },
    role: {
      type: "string",
      enum: [
        "invoice_payer",
        "cash_payer",
        "account_holder",
        "funding_source",
        "intermediary",
        "unknown",
      ],
    },
    found_in_text: { type: "boolean" },
    inferred: { type: "boolean" },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    evidence: { type: "array", items: evidenceSchema },
  },
} as const;

const fundingSourceSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "entity_id",
    "name",
    "entity",
    "entity_kind",
    "origin",
    "distinct_from_invoice_payer",
    "confidence",
    "evidence",
  ],
  properties: {
    entity_id: { type: "string" },
    name: { type: "string" },
    entity: { type: ["string", "null"] },
    entity_kind: { type: "string", enum: ["person", "company", "other"] },
    origin: { type: ["string", "null"] },
    distinct_from_invoice_payer: { type: "boolean" },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    evidence: { type: "array", items: evidenceSchema },
  },
} as const;

export const FORENSIC_JSON_SCHEMA: Record<string, unknown> = {
  type: "object",
  additionalProperties: false,
  required: [
    "document_id",
    "document_hash",
    "language",
    "questions",
    "entities",
    "transactions",
    "transaction_edges",
    "contradictions",
    "warnings",
  ],
  properties: {
    document_id: { type: "string" },
    document_hash: { type: ["string", "null"] },
    language: { type: "string", enum: ["sk", "cs", "en", "other"] },
    missing_evidence: { type: "array", items: { type: "string" } },
    contradicting_evidence: { type: "array", items: evidenceSchema },
    questions: {
      type: "object",
      additionalProperties: false,
      required: ["weapons_flow", "plan_author", "financing"],
      properties: {
        weapons_flow: {
          type: "object",
          additionalProperties: false,
          required: [
            "answer",
            "confirmed_answer",
            "best_supported_candidates",
            "missing_confirmation",
            "status",
            "actors",
            "missing_evidence",
          ],
          properties: {
            answer: { type: ["string", "null"] },
            confirmed_answer: { type: ["string", "null"] },
            best_supported_candidates: { type: "array", items: actorSchema },
            missing_confirmation: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["sufficient", "insufficient_evidence"] },
            actors: { type: "array", items: actorSchema },
            missing_evidence: { type: "array", items: { type: "string" } },
          },
        },
        plan_author: {
          type: "object",
          additionalProperties: false,
          required: [
            "answer",
            "confirmed_answer",
            "best_supported_candidates",
            "missing_confirmation",
            "status",
            "candidates",
            "confidence",
            "evidence",
            "alternative_explanations",
            "missing_evidence",
          ],
          properties: {
            answer: { type: ["string", "null"] },
            confirmed_answer: { type: ["string", "null"] },
            best_supported_candidates: { type: "array", items: planCandidateSchema },
            missing_confirmation: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["sufficient", "insufficient_evidence"] },
            candidates: { type: "array", items: planCandidateSchema },
            confidence: { type: "number", minimum: 0, maximum: 1 },
            evidence: { type: "array", items: evidenceSchema },
            alternative_explanations: {
              type: "array",
              items: { type: "string" },
            },
            missing_evidence: { type: "array", items: { type: "string" } },
          },
        },
        financing: {
          type: "object",
          additionalProperties: false,
          required: [
            "answer",
            "confirmed_answer",
            "best_supported_candidates",
            "missing_confirmation",
            "status",
            "payers",
            "funding_sources",
            "confidence",
            "evidence",
            "missing_evidence",
          ],
          properties: {
            answer: { type: ["string", "null"] },
            confirmed_answer: { type: ["string", "null"] },
            best_supported_candidates: { type: "array", items: payerSchema },
            missing_confirmation: { type: "array", items: { type: "string" } },
            status: { type: "string", enum: ["sufficient", "insufficient_evidence"] },
            payers: { type: "array", items: payerSchema },
            funding_sources: { type: "array", items: fundingSourceSchema },
            confidence: { type: "number", minimum: 0, maximum: 1 },
            evidence: { type: "array", items: evidenceSchema },
            missing_evidence: { type: "array", items: { type: "string" } },
          },
        },
      },
    },
    entities: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["entity_id", "name", "type", "identifiers", "aliases"],
        properties: {
          entity_id: { type: "string" },
          name: { type: "string" },
          type: { type: "string", enum: ["person", "company", "other"] },
          identifiers: { type: "array", items: { type: "string" } },
          aliases: { type: "array", items: { type: "string" } },
        },
      },
    },
    transactions: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "date",
          "amount",
          "currency",
          "invoice_number",
          "license_number",
          "serial_number",
          "payer",
          "payee",
          "purpose",
          "evidence",
        ],
        properties: {
          date: { type: ["string", "null"] },
          amount: { type: ["string", "null"] },
          currency: { type: ["string", "null"] },
          invoice_number: { type: ["string", "null"] },
          license_number: { type: ["string", "null"] },
          serial_number: { type: ["string", "null"] },
          payer: { type: ["string", "null"] },
          payee: { type: ["string", "null"] },
          purpose: { type: ["string", "null"] },
          evidence: { type: "array", items: evidenceSchema },
        },
      },
    },
    transaction_edges: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "edge_id",
          "from_entity_id",
          "to_entity_id",
          "role",
          "date",
          "amount",
          "currency",
          "instrument",
          "evidence",
        ],
        properties: {
          edge_id: { type: "string" },
          from_entity_id: { type: "string" },
          to_entity_id: { type: "string" },
          role: { type: "string", enum: [...WEAPONS_ROLES] },
          date: { type: ["string", "null"] },
          amount: { type: ["string", "null"] },
          currency: { type: ["string", "null"] },
          instrument: {
            type: ["string", "null"],
            enum: ["invoice", "cash", "account", "unknown", null],
          },
          evidence: { type: "array", items: evidenceSchema, minItems: 1 },
        },
      },
    },
    contradictions: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "field",
          "value_a",
          "value_b",
          "source_a",
          "source_b",
          "description",
        ],
        properties: {
          field: { type: "string" },
          value_a: { type: "string" },
          value_b: { type: "string" },
          source_a: { type: "string" },
          source_b: { type: "string" },
          description: { type: "string" },
        },
      },
    },
    warnings: { type: "array", items: { type: "string" } },
  },
};

export const FORENSIC_RESPONSE_FORMAT = {
  type: "json_schema" as const,
  json_schema: {
    name: "forensic_analysis",
    schema: FORENSIC_JSON_SCHEMA,
    strict: true,
  },
};
